### ISSUE TITLE
Create XD Designs

### ISSUE THREAD

**Issue by builtbyproxy** [dwaynediddy/mealapp#1]
https://www.adobe.com/au/products/xd.html

**Comment by builtbyproxy** [comment]
How'd you go with this?

**Comment by builtbyproxy** [comment]
@dwaynediddy Any luck?

**Comment by DwayneBurr** [comment]
Hey I added a couple designs to the app and have tried to get a YouTube video working but think I’m having a problem with cocoa pods, I think I’ve pushed to GitHub. also haven’t heard anything from Amelia either.

**Comment by builtbyproxy** [comment]
Can you please link the XD Designs here?

**Comment by builtbyproxy** [comment]
Nice I see these:
https://github.com/dwaynediddy/mealapp/blob/master/wireframes/planscreen.png

Can you put the XD Link here though?
No need to upload the actual `.png` files 👍

**Comment by DwayneBurr** [comment]
Hey just confirming, meet tomorrow 12?

**Comment by builtbyproxy** [comment]
Hey mate
Just wanted to check in on this, how's it going?

**Comment by DwayneBurr** [comment]
Hey pal, all going good. Haven’t been working on my app have a feeling I’ve been doing stuff just to do it but not understanding a lot so trying to go back to basics.

Hope all is good your end

**Comment by builtbyproxy** [comment]
Fair enough 👍 Glad to hear you're still moving forward! 
Loop me in with whatever you pivot to
